server:
  port: 1001
spring:
  application:
    name: user-server
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10086/eureka,http://localhost:10087/eureka